# Generated by Django 6.0.6 on 2026-06-09 10:54

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import school.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Section identifier, e.g. 'East', 'West', 'A', 'B'", max_length=50)),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
                'ordering': ['stream__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('STEM', 'Science, Technology, Engineering & Mathematics'), ('SS', 'Social Sciences'), ('ASS', 'Arts & Sports Science'), ('GENERAL', 'Junior Secondary / Lower Level Base')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Pathway',
                'verbose_name_plural': 'Pathways',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('admission_number', models.CharField(max_length=50, unique=True)),
                ('date_of_birth', models.DateField(blank=True, help_text='Used for age-grade validation and reporting.', null=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(help_text='e.g., Jane Ngoiri', max_length=150)),
                ('tsc_number', models.CharField(blank=True, help_text='Teachers Service Commission number. Leave blank for Board of Management (BOM) employees.', max_length=50, null=True, unique=True)),
                ('is_hod', models.BooleanField(default=False, help_text='Designates whether this teacher has HOD-level permissions.', verbose_name='Head of Department Status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ClassSubjectAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.PositiveIntegerField(default=school.models._current_year, help_text='Academic year this allocation applies to, e.g. 2026.', validators=[school.models._validate_academic_year])),
                ('term', models.PositiveIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')], help_text='Term this allocation applies to.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('formative_weight', models.DecimalField(decimal_places=2, default=70.0, help_text='Percentage weight of formative (SBA) scores in the final grade. Summative weight is derived as 100 minus this value. KICD default: 70.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_allocations', to='school.classroom')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class–Subject Allocation',
                'verbose_name_plural': 'Class–Subject Allocations',
                'ordering': ['academic_year', 'term', 'classroom', 'subject__name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Volumetric Analysis Practical', 'Mid-Term SBA'", max_length=150)),
                ('task_type', models.CharField(choices=[('FORMATIVE', 'School-Based Assessment – Formative'), ('SUMMATIVE', 'End-of-Term Examination – Summative')], max_length=20)),
                ('max_points', models.PositiveIntegerField(default=100, help_text='Total maximum marks for this task (1–1000)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('date_administered', models.DateField(blank=True, help_text='Date the assessment was sat or submitted.', null=True)),
                ('evaluating_teacher', models.ForeignKey(blank=True, help_text='The teacher who administered and evaluated this task for compliance history.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_tasks', to=settings.AUTH_USER_MODEL)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='school.classsubjectallocation')),
            ],
            options={
                'verbose_name': 'Assessment Task',
                'verbose_name_plural': 'Assessment Tasks',
                'ordering': ['allocation__academic_year', 'allocation__term', 'allocation', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Grade level, e.g. 'Grade 10', 'Grade 11'", max_length=50)),
                ('pathway', models.ForeignKey(blank=True, help_text='The KICD pathway this stream belongs to. Leave blank for junior/lower secondary streams.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='streams', to='school.pathway')),
            ],
            options={
                'verbose_name': 'Stream',
                'verbose_name_plural': 'Streams',
                'ordering': ['name', 'pathway__code'],
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='school.stream'),
        ),
        migrations.CreateModel(
            name='LearnerAssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_achieved', models.DecimalField(decimal_places=2, help_text="Raw numerical score (0 – task's max_points)", max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('teacher_remarks', models.TextField(blank=True, default='', help_text='Qualitative feedback mapping specific competencies')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the result was first entered.')),
                ('last_modified_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the most recent edit — useful for audit trails.')),
                ('assessment_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='school.assessmenttask')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='school.student')),
            ],
            options={
                'verbose_name': 'Learner Assessment Result',
                'verbose_name_plural': 'Learner Assessment Results',
                'ordering': ['assessment_task', 'student__name'],
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.PositiveIntegerField(default=school.models._current_year, help_text='e.g., 2026', validators=[school.models._validate_academic_year])),
                ('term', models.PositiveIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')], help_text='Term in which this placement is effective.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('is_active', models.BooleanField(default=True, help_text='Set to False when a student transfers out mid-term rather than deleting the historical record.')),
                ('enrolled_on', models.DateField(default=django.utils.timezone.now, help_text='Date the enrollment became effective.')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='school.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='school.student')),
            ],
            options={
                'verbose_name': 'Student Enrollment',
                'verbose_name_plural': 'Student Enrollments',
                'ordering': ['academic_year', 'term', 'student__name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Short code e.g. ENG, CHEM, HIST', max_length=20, unique=True)),
                ('learning_area', models.CharField(choices=[('LANG', 'Languages & Literature'), ('CSL', 'Community Service Learning'), ('PE', 'Physical Education'), ('LIFE', 'Life Skills Education'), ('RE', 'Religious Education'), ('MATH', 'Mathematics'), ('BIO', 'Biology'), ('CHEM', 'Chemistry'), ('PHY', 'Physics'), ('CS', 'Computer Science'), ('AGRI', 'Agriculture & Nutrition'), ('TECH', 'Technical & Engineering'), ('HIST', 'History & Citizenship'), ('GEO', 'Geography'), ('BUS', 'Business Studies'), ('ECON', 'Economics'), ('FOREIGN_LANG', 'Foreign Languages'), ('ART', 'Fine Art & Design'), ('PERF', 'Performing Arts'), ('SPORT', 'Sports Science'), ('HOME', 'Home Science'), ('MEDIA', 'Media & Film Technology'), ('FASHION', 'Fashion & Design')], max_length=20)),
                ('category', models.CharField(choices=[('CORE', 'Core Subject'), ('ELECTIVE', 'Elective Subject')], help_text='Core = all students; Elective = pathway-specific', max_length=10)),
                ('pathways', models.ManyToManyField(blank=True, help_text='Leave blank for core subjects (apply to all pathways)', related_name='subjects', to='school.pathway')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentSubjectSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.PositiveIntegerField(default=school.models._current_year, validators=[school.models._validate_academic_year])),
                ('grade', models.PositiveIntegerField(choices=[(10, 'Grade 10'), (11, 'Grade 11'), (12, 'Grade 12')], help_text='SSS grade level for this selection')),
                ('is_approved', models.BooleanField(default=False, help_text='Approved by the class teacher / administration')),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_selections', to='school.pathway')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_selections', to='school.student')),
                ('elective_subjects', models.ManyToManyField(help_text='3–4 elective subjects from the chosen pathway', limit_choices_to={'category': 'ELECTIVE'}, related_name='student_selections', to='school.subject')),
            ],
            options={
                'verbose_name': 'Student Subject Selection',
                'verbose_name_plural': 'Student Subject Selections',
                'ordering': ['academic_year', 'grade', 'student__name'],
            },
        ),
        migrations.AddField(
            model_name='classsubjectallocation',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_allocations', to='school.subject'),
        ),
        migrations.AddConstraint(
            model_name='assessmenttask',
            constraint=models.UniqueConstraint(fields=('allocation', 'title'), name='unique_task_title_per_allocation'),
        ),
        migrations.AddConstraint(
            model_name='stream',
            constraint=models.UniqueConstraint(fields=('name', 'pathway'), name='unique_stream_combination'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('name', 'stream'), name='unique_classroom_section_per_stream'),
        ),
        migrations.AddConstraint(
            model_name='learnerassessmentresult',
            constraint=models.UniqueConstraint(fields=('student', 'assessment_task'), name='unique_student_result_per_task'),
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year', 'term'), name='unique_student_enrollment_per_term'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('name', 'learning_area'), name='unique_subject_per_learning_area'),
        ),
        migrations.AddConstraint(
            model_name='studentsubjectselection',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year', 'grade'), name='unique_selection_per_student_per_year'),
        ),
        migrations.AddConstraint(
            model_name='classsubjectallocation',
            constraint=models.UniqueConstraint(fields=('classroom', 'subject', 'academic_year', 'term'), name='unique_allocation_per_term'),
        ),
    ]
