# Generated by Django 6.0.6 on 2026-06-14 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_add_database_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assessmenttask',
            name='idx_task_allocation_type',
        ),
        migrations.RemoveIndex(
            model_name='assessmenttask',
            name='idx_task_date_administered',
        ),
        migrations.RemoveIndex(
            model_name='classroom',
            name='idx_classroom_stream',
        ),
        migrations.RemoveIndex(
            model_name='classsubjectallocation',
            name='idx_allocation_teacher_year_term',
        ),
        migrations.RemoveIndex(
            model_name='classsubjectallocation',
            name='idx_allocation_classroom_year_term',
        ),
        migrations.RemoveIndex(
            model_name='classsubjectallocation',
            name='idx_allocation_subject',
        ),
        migrations.RemoveIndex(
            model_name='learnerassessmentresult',
            name='idx_result_student_task',
        ),
        migrations.RemoveIndex(
            model_name='learnerassessmentresult',
            name='idx_result_recorded_at',
        ),
        migrations.RemoveIndex(
            model_name='learnerassessmentresult',
            name='idx_result_assessment_task',
        ),
        migrations.RemoveIndex(
            model_name='stream',
            name='idx_stream_pathway',
        ),
        migrations.RemoveIndex(
            model_name='studentenrollment',
            name='idx_studentenrollment_year_term_active',
        ),
        migrations.RemoveIndex(
            model_name='studentenrollment',
            name='idx_studentenrollment_classroom',
        ),
        migrations.RemoveIndex(
            model_name='studentenrollment',
            name='idx_studentenrollment_student',
        ),
        migrations.RemoveIndex(
            model_name='studentsubjectselection',
            name='idx_selection_student_year_grade',
        ),
        migrations.RemoveIndex(
            model_name='studentsubjectselection',
            name='idx_selection_pathway',
        ),
        migrations.RemoveIndex(
            model_name='studentsubjectselection',
            name='idx_selection_is_approved',
        ),
        migrations.RemoveIndex(
            model_name='subject',
            name='idx_subject_category',
        ),
        migrations.RemoveIndex(
            model_name='subject',
            name='idx_subject_learning_area',
        ),
        migrations.RemoveIndex(
            model_name='teacher',
            name='idx_teacher_hod_active',
        ),
        migrations.RemoveIndex(
            model_name='teacher',
            name='idx_teacher_tsc_number',
        ),
    ]
